# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnstrace < Formula
  desc " DNS resolution tracing tool."
  homepage "https://github.com/hatamiarash7/dnstrace"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hatamiarash7/dnstrace/releases/download/v1.1.1/dnstrace_1.1.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "07a454d888aa44565264fd92846ca6cd409632c739bed5e491976dc0a711ed50"

      def install
        bin.install "dnstrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hatamiarash7/dnstrace/releases/download/v1.1.1/dnstrace_1.1.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8e6e3c01ebc17d206c079e8aaad2f227811603baf1a828a9747719ee9f20617f"

      def install
        bin.install "dnstrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hatamiarash7/dnstrace/releases/download/v1.1.1/dnstrace_1.1.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b38ff68acf0e75d608787eca64ff35a59e21e9e774543f5a99a6bc04abf9cb60"

      def install
        bin.install "dnstrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hatamiarash7/dnstrace/releases/download/v1.1.1/dnstrace_1.1.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d2f201a0369be440efbe9359e534a0abb93621fdc97b9de7d067051a11ba7210"

      def install
        bin.install "dnstrace"
      end
    end
  end
end
